module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:import/recommended',
    'plugin:jsonc/recommended-with-jsonc',
    'plugin:eslint-comments/recommended',
  ],
  plugins: ['html'],
  settings: { 'import/resolver': { node: { extensions: ['.js', '.mjs', 'cjs'] } } },
  ignorePatterns: [
    '*.min.*',
    '*.d.ts',
    'dist',
    'output',
    'coverage',
    'public',
    'temp',
    'package-lock.json',
    'yarn.lock',
    '__snapshots__',
    '!.github',
    '!.vitepress',
    '!.vscode',
  ],
  overrides: [
    {
      files: ['*.d.ts'],
      rules: { 'import/no-duplicates': 'off' },
    },
    {
      files: ['*.json', '*.json5'],
      parser: 'jsonc-eslint-parser',
      rules: {
        'jsonc/array-bracket-spacing': ['warn', 'never'],
        'jsonc/comma-dangle': ['warn', 'never'],
        'jsonc/comma-style': ['warn', 'last'],
        'jsonc/indent': ['warn', 2],
        'jsonc/key-spacing': ['warn', { beforeColon: false, afterColon: true }],
        'jsonc/no-octal-escape': 'warn',
        'jsonc/object-curly-newline': ['warn', { multiline: true, consistent: true }],
        'jsonc/object-curly-spacing': ['warn', 'always'],
        'jsonc/object-property-newline': ['warn', { allowMultiplePropertiesPerLine: true }],
      },
    },
    {
      files: ['package.json'],
      parser: 'jsonc-eslint-parser',
      rules: {
        'jsonc/sort-keys': [
          'warn',
          {
            pathPattern: '^$',
            order: [
              'publisher',
              'name',
              'displayName',
              'type',
              'version',
              'private',
              'packageManager',
              'description',
              'author',
              'license',
              'funding',
              'homepage',
              'repository',
              'bugs',
              'keywords',
              'categories',
              'sideEffects',
              'exports',
              'main',
              'module',
              'unpkg',
              'jsdelivr',
              'types',
              'typesVersions',
              'bin',
              'icon',
              'files',
              'engines',
              'activationEvents',
              'contributes',
              'scripts',
              'peerDependencies',
              'peerDependenciesMeta',
              'dependencies',
              'optionalDependencies',
              'devDependencies',
              'pnpm',
              'overrides',
              'resolutions',
              'husky',
              'simple-git-hooks',
              'lint-staged',
              'eslintConfig',
            ],
          },
          {
            pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies$',
            order: { type: 'asc' },
          },
          {
            pathPattern: '^exports.*$',
            order: ['types', 'require', 'import'],
          },
        ],
      },
    },
  ],
  rules: {
    // error
    'no-extra-parens': 'error',

    // best practices
    'accessor-pairs': 'warn',
    'curly': 'warn',
    'no-empty-function': 'warn',
    'require-await': 'warn',

    // variables
    'no-use-before-define': 'error',

    // cmj
    'no-new-require': 'error',

    // stylistic
    'array-element-newline': ['warn', 'consistent'],
    'comma-dangle': ['warn',
      {
        'arrays': 'always-multiline',
        'objects': 'always-multiline',
        'imports': 'always-multiline',
        'exports': 'always-multiline',
        'functions': 'never',
      }],
    'comma-spacing': 'warn',
    'comma-style': 'warn',
    'computed-property-spacing': ['warn', 'never'],
    'eol-last': ['warn', 'never'],
    'func-call-spacing': ['warn', 'never'],
    'indent': ['warn',
      2,
      {
        SwitchCase: 1, VariableDeclarator: 1, outerIIFEBody: 1,
      }],
    'implicit-arrow-linebreak': ['warn', 'beside'],
    'key-spacing': ['warn', { beforeColon: false, afterColon: true }],
    'keyword-spacing': ['warn', { after: true }],
    'lines-between-class-members': ['warn',
      'always',
      { exceptAfterSingleLine: true }],
    'new-cap': ['warn', { newIsCap: true }],
    'no-lonely-if': 'warn',
    'no-mixed-operators': 'warn',
    'no-multiple-empty-lines': ['warn', { max: 1 }],
    'no-negated-condition': 'warn',
    'no-nested-ternary': 'warn',
    'no-trailing-spaces': 'warn',
    'no-unneeded-ternary': 'warn',
    'no-whitespace-before-property': 'warn',
    'nonblock-statement-body-position': ['warn', 'beside'],
    'object-curly-newline': ['warn', { multiline: true, consistent: true }],
    'object-curly-spacing': ['warn', 'always'],
    'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
    'operator-linebreak': ['warn', 'before'],
    'padded-blocks': ['warn', 'never'],
    'quotes': ['warn',
      'single',
      { avoidEscape: true }],
    'semi': ['warn', 'never'],
    'space-before-blocks': ['warn', 'always'],
    'space-before-function-paren': ['warn',
      {
        'anonymous': 'always',
        'named': 'never',
        'asyncArrow': 'always',
      }],
    'space-in-parens': ['warn', 'never'],
    'space-infix-ops': 'warn',
    'space-unary-ops': 'warn',
    'spaced-comment': ['warn', 'always'],
    'switch-colon-spacing': ['warn', { 'after': true, 'before': false }],
    'template-tag-spacing': ['warn', 'never'],

    // esm
    'arrow-spacing': ['warn', { 'before': true, 'after': true }],
    'no-var': 'warn',
    'prefer-const': ['warn',
      {
        'destructuring': 'all',
        'ignoreReadBeforeAssign': true,
      }],
    'rest-spread-spacing': ['warn', 'never'],
  },
}